# Data for multiple states and counties

In our [first notebook](01-census-basics.ipynb), we reviewed the basics of working with the Census API and some important considerations related to margins of error. 

In this notebook, we'll review how to pull data for more than a single state or county. This can be quite handy when you're trying to get a sense of the big-picture nationally, or within a state or region.

> Before proceeding, make sure you've obtained and stored a Census API key per [these instructions](README.md).

In [1]:
import altair as alt
from census import Census
import pandas as pd

from census_api_key import KEY

## Start the Census client

In [2]:
client = Census(KEY)

## Downloading data

So now let's define a few things to make it easier for us to query the API and download the relevant data:

In [3]:
state_fips = '06' # California state FIPS code
county_fips = '085' # FIPS code for Santa Clara County

We also need to specify what fields we want to download from the table we've identified. I like to do this in a dictionary where the keys are the variable IDs and the values are human-readable names of the variables. I do this so I can easily see what these are in my code and to make renaming columns easier later on.

In [4]:
fields = {
    'B19013_001E': 'median_hh_income',
    'B19013_001M': 'margin_of_error',
}
# I also create a list of the variable IDs to give to the Census client
field_codes = list(fields.keys())

## Downloading multiple geographic areas

Often we don't want to look at a single county or state. We can easily download all states in the nation, or counties in a state using a property of the Python Census library - `Census.ALL`. This is exactly the same as using `'*'` which is traditionally viewed as a character to represent wildcards.

### Download all states

In [5]:
raw = client.acs5.state(field_codes, Census.ALL)
len(raw)

52

In [6]:
data = pd.DataFrame(raw).rename(columns=fields)
data.head()

   median_hh_income  margin_of_error state
0           59609.0            377.0    01
1           86370.0           1083.0    02
2           72581.0            450.0    04
3           56335.0            422.0    05
4           91905.0            277.0    06

We don't have state names with this data, only FIPS codes. We can easily use the crosswalk the Census Bureau provides. The crosswalk is a pipe-delimited text file we can load directly into Pandas without downloading.

In [7]:
state_fips_url = 'https://www2.census.gov/geo/docs/reference/codes2020/national_state2020.txt'
# Notice we specified `|` for the delimiter
# We are also going to set the data type of all columns as a string 
# to keep leading zeroes in identifiers
state_codes = pd.read_csv(state_fips_url, delimiter='|', dtype=str) 
state_codes.head()

  STATE STATEFP   STATENS  STATE_NAME
0    AL      01  01779775     Alabama
1    AK      02  01785533      Alaska
2    AZ      04  01779777     Arizona
3    AR      05  00068085    Arkansas
4    CA      06  01779778  California

Let's merge these together.

In [8]:
merged = data.merge(
    state_codes,
    how='left',
    left_on='state',
    right_on='STATEFP'
)
merged.head()

   median_hh_income  margin_of_error state STATE STATEFP   STATENS  STATE_NAME
0           59609.0            377.0    01    AL      01  01779775     Alabama
1           86370.0           1083.0    02    AK      02  01785533      Alaska
2           72581.0            450.0    04    AZ      04  01779777     Arizona
3           56335.0            422.0    05    AR      05  00068085    Arkansas
4           91905.0            277.0    06    CA      06  01779778  California

Great we can now write out our results to a file for later use.

In [9]:
merged.to_csv('./median_hh_income_states.csv', index=False)

### Download multiple counties

The process is very similar to above, only we use the client's `state_county` method to get county-level data.

#### For a single state

In [10]:
raw = client.acs5.state_county(field_codes, state_fips, Census.ALL)
len(raw)

58

#### For all states

In [11]:
raw = client.acs5.state_county(field_codes, Census.ALL, Census.ALL)
len(raw)

3222

In [12]:
data = pd.DataFrame(raw).rename(columns=fields)
data

      median_hh_income  margin_of_error state county
0              68315.0           4941.0    01    001
1              71039.0           2374.0    01    003
2              39712.0           3289.0    01    005
3              50669.0           8260.0    01    007
4              57440.0           3308.0    01    009
...                ...              ...   ...    ...
3217           23701.0           1606.0    72    145
3218           17062.0            999.0    72    147
3219           22461.0           3326.0    72    149
3220           19972.0           1975.0    72    151
3221           19827.0           1671.0    72    153

[3222 rows x 4 columns]

#### Add county names

We can also use FIPS codes to add county and state names. We will use a different dataset this time that includes county FIPS codes.

In [13]:
county_fips_url = 'https://www2.census.gov/geo/docs/reference/codes2020/national_county2020.txt'
county_codes = pd.read_csv(county_fips_url, delimiter='|', dtype=str)
county_codes

     STATE STATEFP COUNTYFP  COUNTYNS         COUNTYNAME CLASSFP FUNCSTAT
0       AL      01      001  00161526     Autauga County      H1        A
1       AL      01      003  00161527     Baldwin County      H1        A
2       AL      01      005  00161528     Barbour County      H1        A
3       AL      01      007  00161529        Bibb County      H1        A
4       AL      01      009  00161530      Blount County      H1        A
...    ...     ...      ...       ...                ...     ...      ...
3230    PR      72      153  01804557    Yauco Municipio      H1        A
3231    UM      74      300  01802699     Midway Islands      H4        N
3232    VI      78      010  02378248   St. Croix Island      H4        N
3233    VI      78      020  02378249    St. John Island      H4        N
3234    VI      78      030  02378250  St. Thomas Island      H4        N

[3235 rows x 7 columns]

County FIPS codes are unique within a state, but not nationally. So we need to include both state and county FIPS codes when joining the data.

In [14]:
data['geoid'] = data['state'] + data['county']
data.head()

   median_hh_income  margin_of_error state county  geoid
0           68315.0           4941.0    01    001  01001
1           71039.0           2374.0    01    003  01003
2           39712.0           3289.0    01    005  01005
3           50669.0           8260.0    01    007  01007
4           57440.0           3308.0    01    009  01009

In [15]:
county_codes['geoid'] = county_codes['STATEFP'] + county_codes['COUNTYFP']
county_codes

,STATE,STATEFP,COUNTYFP,COUNTYNS,COUNTYNAME,CLASSFP,FUNCSTAT,geoid
0,AL,01,001,00161526,Autauga County,H1,A,01001
1,AL,01,003,00161527,Baldwin County,H1,A,01003
2,AL,01,005,00161528,Barbour County,H1,A,01005
3,AL,01,007,00161529,Bibb County,H1,A,01007
4,AL,01,009,00161530,Blount County,H1,A,01009
...,...,...,...,...,...,...,...,...
3230,PR,72,153,01804557,Yauco Municipio,H1,A,72153
3231,UM,74,300,01802699,Midway Islands,H4,N,74300
3232,VI,78,010,02378248,St. Croix Island,H4,N,78010
3233,VI,78,020,02378249,St. John Island,H4,N,78020
3234,VI,78,030,02378250,St. Thomas Island,H4,N,78030

Now we can join the two dataframes as we did above using the `geoid` columns we just created.

In [16]:
merged = data.merge(
    county_codes,
    how='left',
    on='geoid'
)
merged.head()

,median_hh_income,margin_of_error,state,county,geoid,STATE,STATEFP,COUNTYFP,COUNTYNS,COUNTYNAME,CLASSFP,FUNCSTAT
0,68315.0,4941.0,01,001,01001,AL,01,001,00161526,Autauga County,H1,A
1,71039.0,2374.0,01,003,01003,AL,01,003,00161527,Baldwin County,H1,A
2,39712.0,3289.0,01,005,01005,AL,01,005,00161528,Barbour County,H1,A
3,50669.0,8260.0,01,007,01007,AL,01,007,00161529,Bibb County,H1,A
4,57440.0,3308.0,01,009,01009,AL,01,009,00161530,Blount County,H1,A

And once again write out our data:

In [17]:
merged.to_csv('./median_hh_income_counties.csv', index=False)